development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: esm_test
  pool: 5
  username: esm_test

production:
  adapter: postgresql
  database: esm_production
  pool: 5
  username: esm_production
